name:       csv-language-project
version:    0.1.0.0
github:     "mh6n23/PLC-CW"
license:    BSD-3-Clause
author:     "Matthew Heath"
maintainer: "mh6n23@soton.ac.uk"
copyright:  "University of Southampton"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package:
# synopsis: Short description of your package
# category: Web

description: Alex and Happy project.

dependencies:
- base >= 4.7 && < 5
- array
- split # added by Matt
- MissingH # added by Matt (used for strip function)
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
  csv-language-project-exe:
    main: Interpreter.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv-language-project

tests:
  csv-language-project-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv-language-project
